name: flutter_webp
description: Asset transformer for converting images into WebP files.
version: 0.0.1
repository: https://github.com/leancodepl/flutter_webp

executables:
  flutter_webp:
    
environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
