name: webp
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/leancodepl/flutter_webp

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
