name: webp
description: Asset transformer for converting images into WebP files.
version: 0.1.0
repository: https://github.com/leancodepl/flutter_webp

executables:
  webp:
    
environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  leancode_lint: ^12.0.0
  test: ^1.24.0
