name: Prepare

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: latest
                  channel: stable

            - name: Install dependencies
              run: flutter pub get

            - name: Verify formatting
              run: dart format --set-exit-if-changed .

            - name: Analyze
              run: flutter analyze

            - name: Dry run pub publish
              # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
              run: dart pub publish --dry-run || true
