name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    name: Publish to pub.dev

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.4

      - name: Download cwebp
        run:
          mkdir tmp
          cd tmp

          curl https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0-windows-x64.zip
          curl https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0-rc1-mac-x86-64.tar.gz
          curl https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0-rc1-mac-arm64.tar.gz
          curl https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0-linux-x86-64.tar.gz
          curl https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0-linux-aarch64.tar.gz

          tar -zf libwebp-1.4.0-windows-x64.zip
          tar -xzf libwebp-1.4.0-rc1-mac-x86-64.tar.gz
          tar -xzf libwebp-1.4.0-rc1-mac-arm64.tar.gz
          tar -xzf libwebp-1.4.0-linux-x86-64.tar.gz
          tar -xzf libwebp-1.4.0-linux-aarch64.tar.gz

          cd ..

          mv tmp/libwebp-1.4.0-windows-x64/libwebp-1.4.0-windows-x64/bin/cwebp.exe windows-x64/
          mv tmp/libwebp-1.4.0-rc1-mac-x86-64/libwebp-1.4.0-rc1-mac-x86-64/bin/cwebp.exe mac-x86-64/
          mv tmp/libwebp-1.4.0-rc1-mac-arm64/libwebp-1.4.0-rc1-mac-arm64/bin/cwebp.exe mac-arm64/
          mv tmp/libwebp-1.4.0-linux-x86-64/libwebp-1.4.0-linux-x86-64/bin/cwebp.exe linux-x86-64/
          mv tmp/libwebp-1.4.0-linux-aarch64/libwebp-1.4.0-linux-aarch64/bin/cwebp.exe linux-aarch64/

          rm -r tmp

      - name: Publish and release
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
